/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.Database;
import controller.ThuatToan;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import models.ThongBao;

/**
 *
 * @author Dat
 */
public final class FormDoiHanNop extends javax.swing.JFrame {
    private ArrayList<ThongBao> dsThongBao;
    private int thuTu;
    private JTable table;

    /**
     * Creates new form FormDoiHanNop
     * @throws java.text.ParseException
     */
    public FormDoiHanNop() throws ParseException {
        initComponents();
        edit();
    }
    
    public FormDoiHanNop(ArrayList <ThongBao> dsThongBao, JTable table, int thuTu) throws ParseException {
        initComponents();
        this.dsThongBao = dsThongBao;
        this.thuTu = thuTu;
        this.table = table;
        edit();
    }
    
    public void edit() throws ParseException{
        setLocationRelativeTo(null);
        ThongBao tb = dsThongBao.get(dsThongBao.size() - thuTu - 1);
        System.out.println(tb.getNgayKTCS());
        
        String dateString;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date;
        if(!tb.getNgayBD().equals("")){
            dateString = tb.getNgayBD();
            date = sdf.parse(dateString);
            jDateChooserNgayBD.setDate(date);
            jDateChooserNgayBD.setDateFormatString("dd-MM-yyyy");
        }
        if(!tb.getNgayKTSV().equals("")){
            dateString = tb.getNgayKTSV();
            date = sdf.parse(dateString);
            jDateChooserHanSV.setDate(date);
            jDateChooserHanSV.setDateFormatString("dd-MM-yyyy");
        }
        if(!tb.getNgayKTCS().equals("")){
            dateString = tb.getNgayKTCS();
            date = sdf.parse(dateString);
            jDateChooserHanCS.setDate(date);
            jDateChooserHanCS.setDateFormatString("dd-MM-yyyy");
        }
        if(!tb.getNgayKTCV().equals("")){
            dateString = tb.getNgayKTCV();
            date = sdf.parse(dateString);
            jDateChooserHanCV.setDate(date);
            jDateChooserHanCV.setDateFormatString("dd-MM-yyyy");
        }
        if(!tb.getNgayKTKhoa().equals("")){
            dateString = tb.getNgayKTKhoa();
            date = sdf.parse(dateString);
            jDateChooserHanKhoa.setDate(date);
            jDateChooserHanKhoa.setDateFormatString("dd-MM-yyyy");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelView = new javax.swing.JPanel();
        jPanelThanhTieuDeTieuChi = new javax.swing.JPanel();
        jPanelNutTieuDeTieuChi = RoundedPanel.createRoundedPanel();
        jLabelNutTieuDeTieuChi = new javax.swing.JLabel();
        jPanelNutLuu = RoundedPanel.createRoundedPanel();
        jLabelNutLuu = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabelNgayBD = new javax.swing.JLabel();
        jDateChooserNgayBD = new com.toedter.calendar.JDateChooser();
        jLabelHanSV = new javax.swing.JLabel();
        jDateChooserHanSV = new com.toedter.calendar.JDateChooser();
        jLabelHanCS = new javax.swing.JLabel();
        jDateChooserHanCS = new com.toedter.calendar.JDateChooser();
        jLabelHanCV = new javax.swing.JLabel();
        jDateChooserHanCV = new com.toedter.calendar.JDateChooser();
        jLabelHanCV1 = new javax.swing.JLabel();
        jDateChooserHanKhoa = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelThanhTieuDeTieuChi.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThanhTieuDeTieuChi.setPreferredSize(new java.awt.Dimension(770, 34));

        jPanelNutTieuDeTieuChi.setBackground(new java.awt.Color(221, 51, 51));

        jLabelNutTieuDeTieuChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNutTieuDeTieuChi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNutTieuDeTieuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whitecalender.png"))); // NOI18N
        jLabelNutTieuDeTieuChi.setText("Tùy chỉnh hạn nộp");
        jLabelNutTieuDeTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLabelNutTieuDeTieuChi.setPreferredSize(new java.awt.Dimension(32, 16));

        javax.swing.GroupLayout jPanelNutTieuDeTieuChiLayout = new javax.swing.GroupLayout(jPanelNutTieuDeTieuChi);
        jPanelNutTieuDeTieuChi.setLayout(jPanelNutTieuDeTieuChiLayout);
        jPanelNutTieuDeTieuChiLayout.setHorizontalGroup(
            jPanelNutTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutTieuDeTieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNutTieuDeTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNutTieuDeTieuChiLayout.setVerticalGroup(
            jPanelNutTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNutTieuDeTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanelNutLuu.setBackground(new java.awt.Color(221, 51, 51));
        jPanelNutLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelNutLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNutLuu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNutLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whitesave.png"))); // NOI18N
        jLabelNutLuu.setText("Lưu");
        jLabelNutLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNutLuu.setPreferredSize(new java.awt.Dimension(32, 16));
        jLabelNutLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNutLuuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelNutLuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelNutLuuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelNutLuuLayout = new javax.swing.GroupLayout(jPanelNutLuu);
        jPanelNutLuu.setLayout(jPanelNutLuuLayout);
        jPanelNutLuuLayout.setHorizontalGroup(
            jPanelNutLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutLuuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNutLuu, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        jPanelNutLuuLayout.setVerticalGroup(
            jPanelNutLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNutLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelThanhTieuDeTieuChiLayout = new javax.swing.GroupLayout(jPanelThanhTieuDeTieuChi);
        jPanelThanhTieuDeTieuChi.setLayout(jPanelThanhTieuDeTieuChiLayout);
        jPanelThanhTieuDeTieuChiLayout.setHorizontalGroup(
            jPanelThanhTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThanhTieuDeTieuChiLayout.createSequentialGroup()
                .addComponent(jPanelNutTieuDeTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelNutLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelThanhTieuDeTieuChiLayout.setVerticalGroup(
            jPanelThanhTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNutTieuDeTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNutLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabelNgayBD.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabelNgayBD.setText("Ngày bắt đầu xét:");

        jDateChooserNgayBD.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserNgayBD.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserNgayBDPropertyChange(evt);
            }
        });
        jDateChooserNgayBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooserNgayBDKeyReleased(evt);
            }
        });

        jLabelHanSV.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabelHanSV.setText("Hạn nộp của sinh viên:");

        jDateChooserHanSV.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserHanSV.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserHanSVPropertyChange(evt);
            }
        });
        jDateChooserHanSV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooserHanSVKeyReleased(evt);
            }
        });

        jLabelHanCS.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabelHanCS.setText("Hạn nộp của ban cán sự lớp:");

        jDateChooserHanCS.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserHanCS.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserHanCSPropertyChange(evt);
            }
        });
        jDateChooserHanCS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooserHanCSKeyReleased(evt);
            }
        });

        jLabelHanCV.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabelHanCV.setText("Hạn nộp của cố vấn học tập:");

        jDateChooserHanCV.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserHanCV.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserHanCVPropertyChange(evt);
            }
        });
        jDateChooserHanCV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooserHanCVKeyReleased(evt);
            }
        });

        jLabelHanCV1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabelHanCV1.setText("Hạn duyệt điểm của khoa");

        jDateChooserHanKhoa.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserHanKhoa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserHanKhoaPropertyChange(evt);
            }
        });
        jDateChooserHanKhoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooserHanKhoaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNgayBD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserHanSV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHanSV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserHanCS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHanCS)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserHanCV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHanCV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserHanKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHanCV1))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgayBD)
                    .addComponent(jLabelHanSV)
                    .addComponent(jLabelHanCS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserHanSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserHanCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHanCV1)
                    .addComponent(jLabelHanCV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserHanCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserHanKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelThanhTieuDeTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelThanhTieuDeTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelNutLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNutLuuMouseClicked
        if (jDateChooserHanCV.getDate() == null ||
                jDateChooserHanKhoa.getDate() == null ||
                jDateChooserNgayBD.getDate() == null ||
                jDateChooserHanSV.getDate() == null ||
                jDateChooserHanCS.getDate() == null) {
            // Nếu tất cả các ngày được chọn đều hợp lệ, thực hiện hành động tiếp theo ở đây
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
                return;
        }
        // Lấy các ngày từ jDateChooser
        Date dateHanCV = jDateChooserHanCV.getDate();
        Date dateHanKhoa = jDateChooserHanKhoa.getDate();
        Date dateNgayBD = jDateChooserNgayBD.getDate();
        Date dateHanSV = jDateChooserHanSV.getDate();
        Date dateHanCS = jDateChooserHanCS.getDate();

        // Kiểm tra điều kiện so sánh
        if (dateNgayBD.compareTo(dateHanSV) < 0 &&
            dateNgayBD.compareTo(dateHanCS) < 0 &&
            dateNgayBD.compareTo(dateHanCV) < 0 &&
            dateNgayBD.compareTo(dateHanKhoa) < 0 &&
            dateHanSV.compareTo(dateHanCS) < 0 &&
            dateHanSV.compareTo(dateHanCV) < 0 &&
            dateHanSV.compareTo(dateHanKhoa) < 0 &&
            dateHanCS.compareTo(dateHanCV) < 0 &&
            dateHanCS.compareTo(dateHanKhoa) < 0 &&
            dateHanCV.compareTo(dateHanKhoa) < 0 ) {
            // Nếu mỗi ngày sau lớn hơn ngày trước, thực hiện hành động tiếp theo ở đây
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ngày không đúng theo thứ tự");
            return;
        }
        
        
        if(JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn đổi không?") == JOptionPane.YES_OPTION){
            new Thread(() -> {
                String day = ThuatToan.getDate((java.util.Date)jDateChooserNgayBD.getDate());
                dsThongBao.get(dsThongBao.size() - thuTu - 1).setNgayBD(day);
                day = ThuatToan.getDate((java.util.Date)jDateChooserHanSV.getDate());
                dsThongBao.get(dsThongBao.size() - thuTu - 1).setNgayKTSV(day);
                day = ThuatToan.getDate((java.util.Date)jDateChooserHanCS.getDate());
                dsThongBao.get(dsThongBao.size() - thuTu - 1).setNgayKTCS(day);
                day = ThuatToan.getDate((java.util.Date)jDateChooserHanCV.getDate());
                dsThongBao.get(dsThongBao.size() - thuTu - 1).setNgayKTCV(day);
                day = ThuatToan.getDate((java.util.Date)jDateChooserHanKhoa.getDate());
                dsThongBao.get(dsThongBao.size() - thuTu - 1).setNgayKTKhoa(day);

                Database.addListThongBaoToTable(dsThongBao, table);
                Database.saveListThongBaoToDB(dsThongBao);
            }).start();
            
            this.dispose();
        }            
        
    }//GEN-LAST:event_jLabelNutLuuMouseClicked

    private void jLabelNutLuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNutLuuMouseEntered
        // TODO add your handling code here:
        jPanelNutLuu.setBackground(new Color(30,115,190));
    }//GEN-LAST:event_jLabelNutLuuMouseEntered

    private void jLabelNutLuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNutLuuMouseExited
        // TODO add your handling code here:
        jPanelNutLuu.setBackground(new Color(221,51,51));
    }//GEN-LAST:event_jLabelNutLuuMouseExited

    private void jDateChooserNgayBDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserNgayBDPropertyChange

    }//GEN-LAST:event_jDateChooserNgayBDPropertyChange

    private void jDateChooserNgayBDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserNgayBDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserNgayBDKeyReleased

    private void jDateChooserHanSVPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserHanSVPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanSVPropertyChange

    private void jDateChooserHanSVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserHanSVKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanSVKeyReleased

    private void jDateChooserHanCSPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserHanCSPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanCSPropertyChange

    private void jDateChooserHanCSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserHanCSKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanCSKeyReleased

    private void jDateChooserHanCVPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserHanCVPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanCVPropertyChange

    private void jDateChooserHanCVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserHanCVKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanCVKeyReleased

    private void jDateChooserHanKhoaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserHanKhoaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanKhoaPropertyChange

    private void jDateChooserHanKhoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserHanKhoaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserHanKhoaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDoiHanNop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDoiHanNop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDoiHanNop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDoiHanNop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FormDoiHanNop().setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(FormDoiHanNop.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooserHanCS;
    private com.toedter.calendar.JDateChooser jDateChooserHanCV;
    private com.toedter.calendar.JDateChooser jDateChooserHanKhoa;
    private com.toedter.calendar.JDateChooser jDateChooserHanSV;
    private com.toedter.calendar.JDateChooser jDateChooserNgayBD;
    private javax.swing.JLabel jLabelHanCS;
    private javax.swing.JLabel jLabelHanCV;
    private javax.swing.JLabel jLabelHanCV1;
    private javax.swing.JLabel jLabelHanSV;
    private javax.swing.JLabel jLabelNgayBD;
    private javax.swing.JLabel jLabelNutLuu;
    private javax.swing.JLabel jLabelNutTieuDeTieuChi;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNutLuu;
    private javax.swing.JPanel jPanelNutTieuDeTieuChi;
    private javax.swing.JPanel jPanelThanhTieuDeTieuChi;
    private javax.swing.JPanel jPanelView;
    // End of variables declaration//GEN-END:variables
}
