/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.raven.swing.ScrollBar;
import icons.Icon;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.util.ArrayList;
import models.NoiDungTieuChi;
import controller.Database;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import models.TieuChi;
/**
 *
 * @author Dat
 */


public final class FormNoiDungTieuChi extends javax.swing.JFrame {
    private ArrayList <TieuChi> dsTieuChi;
    private static final long serialVersionUID = 1L;
    private String title;
    private int ttTC;
    private ArrayList<NoiDungTieuChi> dsNoiDung;
    
    public void edit(){
        setLocationRelativeTo(null);
        JFrame.setDefaultLookAndFeelDecorated(true);
        ImageIcon icon = new ImageIcon(Icon.getUrlIcon("logo_ptit.png")); // Thay "logo.png" bằng đường dẫn của hình ảnh của bạn
        Image logo = icon.getImage();
        this.setIconImage(logo);
        jLabelTitleTieuChi.setText(title);
        Database.addListGiaiThichToTable(dsNoiDung, jTableTieuChi);
        buttonHoverEvent(jLabelNutThemTieuChi, jPanelNutThemTieuChi);
        buttonHoverEvent(jLabelNutSuaTieuChi, jPanelNutSuaTieuChi);
        buttonHoverEvent(jLabelNutXoaTieuChi, jPanelNutXoaTieuChi);

    }
    public FormNoiDungTieuChi() {
        initComponents();
        edit();
    }
    
    public FormNoiDungTieuChi(ArrayList <TieuChi> dsTieuChi, ArrayList<NoiDungTieuChi> dsNoiDung, String title, int ttTC) {
        initComponents();
        this.dsTieuChi = dsTieuChi;
        this.dsNoiDung = dsNoiDung;
        this.title = title;
        this.ttTC = ttTC;
        edit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelBorderTieuChi = new com.raven.swing.PanelBorder();
        jScrollPaneTieuChi = new javax.swing.JScrollPane();
        jTableTieuChi = new com.raven.swing.TableGTTC();
        jLabelTitleTieuChi = new javax.swing.JLabel();
        jPanelThanhTieuDeTieuChi = new javax.swing.JPanel();
        jPanelNutTieuDeTieuChi = RoundedPanel.createRoundedPanel();
        jLabelNutTieuDeTieuChi = new javax.swing.JLabel();
        jPanelNutXoaTieuChi = RoundedPanel.createRoundedPanel();
        jLabelNutXoaTieuChi = new javax.swing.JLabel();
        jPanelNutSuaTieuChi = RoundedPanel.createRoundedPanel();
        jLabelNutSuaTieuChi = new javax.swing.JLabel();
        jPanelNutThemTieuChi = RoundedPanel.createRoundedPanel();
        jLabelNutThemTieuChi = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Giải thích tiêu chí");

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBorderTieuChi.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneTieuChi.setBorder(null);

        jTableTieuChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nội dung", "Điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTieuChi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTieuChi.setShowGrid(true);
        jTableTieuChi.setShowHorizontalLines(true);
        jScrollPaneTieuChi.setViewportView(jTableTieuChi);

        jLabelTitleTieuChi.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelTitleTieuChi.setForeground(new java.awt.Color(127, 127, 127));
        jLabelTitleTieuChi.setText("Thực hiện nghiêm túc các nội quy, quy chế, các quy định hiện hành trong Học viện.");

        javax.swing.GroupLayout jPanelBorderTieuChiLayout = new javax.swing.GroupLayout(jPanelBorderTieuChi);
        jPanelBorderTieuChi.setLayout(jPanelBorderTieuChiLayout);
        jPanelBorderTieuChiLayout.setHorizontalGroup(
            jPanelBorderTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorderTieuChiLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanelBorderTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitleTieuChi)
                    .addComponent(jScrollPaneTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanelBorderTieuChiLayout.setVerticalGroup(
            jPanelBorderTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorderTieuChiLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelTitleTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPaneTieuChi.setVerticalScrollBar(new ScrollBar());
        jScrollPaneTieuChi.getVerticalScrollBar().setBackground(Color.WHITE);
        jScrollPaneTieuChi.getViewport().setBackground(Color.WHITE);
        JPanel p19 = new JPanel();
        p19.setBackground(Color.WHITE);
        jScrollPaneTieuChi.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p19);

        jPanelMain.add(jPanelBorderTieuChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 760, 300));

        jPanelThanhTieuDeTieuChi.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThanhTieuDeTieuChi.setPreferredSize(new java.awt.Dimension(770, 34));

        jPanelNutTieuDeTieuChi.setBackground(new java.awt.Color(221, 51, 51));

        jLabelNutTieuDeTieuChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNutTieuDeTieuChi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNutTieuDeTieuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whitetieuchi.png"))); // NOI18N
        jLabelNutTieuDeTieuChi.setText("Tiêu chí");
        jLabelNutTieuDeTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLabelNutTieuDeTieuChi.setPreferredSize(new java.awt.Dimension(32, 16));

        javax.swing.GroupLayout jPanelNutTieuDeTieuChiLayout = new javax.swing.GroupLayout(jPanelNutTieuDeTieuChi);
        jPanelNutTieuDeTieuChi.setLayout(jPanelNutTieuDeTieuChiLayout);
        jPanelNutTieuDeTieuChiLayout.setHorizontalGroup(
            jPanelNutTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNutTieuDeTieuChiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelNutTieuDeTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNutTieuDeTieuChiLayout.setVerticalGroup(
            jPanelNutTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNutTieuDeTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelNutXoaTieuChi.setBackground(new java.awt.Color(221, 51, 51));
        jPanelNutXoaTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelNutXoaTieuChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNutXoaTieuChi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNutXoaTieuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whitedelete.png"))); // NOI18N
        jLabelNutXoaTieuChi.setText("Xóa");
        jLabelNutXoaTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNutXoaTieuChi.setPreferredSize(new java.awt.Dimension(32, 16));
        jLabelNutXoaTieuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNutXoaTieuChiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNutXoaTieuChiLayout = new javax.swing.GroupLayout(jPanelNutXoaTieuChi);
        jPanelNutXoaTieuChi.setLayout(jPanelNutXoaTieuChiLayout);
        jPanelNutXoaTieuChiLayout.setHorizontalGroup(
            jPanelNutXoaTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutXoaTieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNutXoaTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );
        jPanelNutXoaTieuChiLayout.setVerticalGroup(
            jPanelNutXoaTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNutXoaTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelNutSuaTieuChi.setBackground(new java.awt.Color(221, 51, 51));
        jPanelNutSuaTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelNutSuaTieuChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNutSuaTieuChi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNutSuaTieuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whitewrite.png"))); // NOI18N
        jLabelNutSuaTieuChi.setText("Cập nhật");
        jLabelNutSuaTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNutSuaTieuChi.setPreferredSize(new java.awt.Dimension(32, 16));
        jLabelNutSuaTieuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNutSuaTieuChiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNutSuaTieuChiLayout = new javax.swing.GroupLayout(jPanelNutSuaTieuChi);
        jPanelNutSuaTieuChi.setLayout(jPanelNutSuaTieuChiLayout);
        jPanelNutSuaTieuChiLayout.setHorizontalGroup(
            jPanelNutSuaTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutSuaTieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNutSuaTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
        );
        jPanelNutSuaTieuChiLayout.setVerticalGroup(
            jPanelNutSuaTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNutSuaTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelNutThemTieuChi.setBackground(new java.awt.Color(221, 51, 51));
        jPanelNutThemTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelNutThemTieuChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNutThemTieuChi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNutThemTieuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whiteplus.png"))); // NOI18N
        jLabelNutThemTieuChi.setText("Thêm");
        jLabelNutThemTieuChi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNutThemTieuChi.setPreferredSize(new java.awt.Dimension(32, 16));
        jLabelNutThemTieuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNutThemTieuChiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNutThemTieuChiLayout = new javax.swing.GroupLayout(jPanelNutThemTieuChi);
        jPanelNutThemTieuChi.setLayout(jPanelNutThemTieuChiLayout);
        jPanelNutThemTieuChiLayout.setHorizontalGroup(
            jPanelNutThemTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutThemTieuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNutThemTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );
        jPanelNutThemTieuChiLayout.setVerticalGroup(
            jPanelNutThemTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNutThemTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelThanhTieuDeTieuChiLayout = new javax.swing.GroupLayout(jPanelThanhTieuDeTieuChi);
        jPanelThanhTieuDeTieuChi.setLayout(jPanelThanhTieuDeTieuChiLayout);
        jPanelThanhTieuDeTieuChiLayout.setHorizontalGroup(
            jPanelThanhTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThanhTieuDeTieuChiLayout.createSequentialGroup()
                .addComponent(jPanelNutTieuDeTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jPanelNutThemTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNutSuaTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNutXoaTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelThanhTieuDeTieuChiLayout.setVerticalGroup(
            jPanelThanhTieuDeTieuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNutTieuDeTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNutXoaTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNutSuaTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNutThemTieuChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelThanhTieuDeTieuChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 764, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelNutXoaTieuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNutXoaTieuChiMouseClicked
        // TODO add your handling code here:
        int chon = jTableTieuChi.getSelectedRow();
        if(chon == -1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn nội dung cần xóa!");
        }else{
            if(JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn xóa không?") == JOptionPane.YES_OPTION){
                new Thread(() -> {
                    dsNoiDung.remove(chon);
                    Database.addListGiaiThichToTable(dsNoiDung, jTableTieuChi);
                    dsTieuChi.get(ttTC).setDsNoiDung(dsNoiDung);
                    Database.saveTieuChiToDB(dsTieuChi);
                }).start();
                
           }
        }
    }//GEN-LAST:event_jLabelNutXoaTieuChiMouseClicked

    private void jLabelNutThemTieuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNutThemTieuChiMouseClicked
        // TODO add your handling code here:
        new FormThem_SuaTieuChi(dsTieuChi, jTableTieuChi, ttTC, jTableTieuChi).setVisible(true);
        
    }//GEN-LAST:event_jLabelNutThemTieuChiMouseClicked

    public  void buttonHoverEvent(JLabel label, JPanel panel){
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                panel.setBackground(new Color(30,115,190));
                panel.revalidate(); // Cập nhật giao diện
                panel.repaint();    // Vẽ lại giao diện
            }
        });
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                panel.setBackground(new Color(30,115,190));
                panel.revalidate(); // Cập nhật giao diện
                panel.repaint();    // Vẽ lại giao diện
            }
        });
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseExited(MouseEvent e) {
                panel.setBackground(new Color(221,51,51));
                panel.revalidate(); // Cập nhật giao diện
                panel.repaint();    // Vẽ lại giao diện
            }
        });
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseExited(MouseEvent e) {
                panel.setBackground(new Color(221,51,51));
                panel.revalidate(); // Cập nhật giao diện
                panel.repaint();    // Vẽ lại giao diện
            }
        });
    }
    
    private void jLabelNutSuaTieuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNutSuaTieuChiMouseClicked
        // TODO add your handling code here:
        int chonND = jTableTieuChi.getSelectedRow();
        new FormThem_SuaTieuChi(dsTieuChi, ttTC, jTableTieuChi, chonND).setVisible(true);
    }//GEN-LAST:event_jLabelNutSuaTieuChiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNoiDungTieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNoiDungTieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNoiDungTieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNoiDungTieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormNoiDungTieuChi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNutSuaTieuChi;
    private javax.swing.JLabel jLabelNutThemTieuChi;
    private javax.swing.JLabel jLabelNutTieuDeTieuChi;
    private javax.swing.JLabel jLabelNutXoaTieuChi;
    private javax.swing.JLabel jLabelTitleTieuChi;
    private com.raven.swing.PanelBorder jPanelBorderTieuChi;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNutSuaTieuChi;
    private javax.swing.JPanel jPanelNutThemTieuChi;
    private javax.swing.JPanel jPanelNutTieuDeTieuChi;
    private javax.swing.JPanel jPanelNutXoaTieuChi;
    private javax.swing.JPanel jPanelThanhTieuDeTieuChi;
    private javax.swing.JScrollPane jScrollPaneTieuChi;
    private com.raven.swing.Table jTableTieuChi;
    // End of variables declaration//GEN-END:variables
}
