/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import models.CoVan;
import models.Khoa;
import models.KhoaHoc;
import models.Lop;
import controller.Controller;
import java.awt.Choice;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Dat
 */
public final class SuaLop extends javax.swing.JFrame {

    /**
     * Creates new form ThemLop
     */
    private Choice choice;
    private JTable table;
    private int chon;
    private ArrayList <Khoa> dsKhoa = null;
    private ArrayList <CoVan> dsCoVan = null;
    private ArrayList <KhoaHoc> dsKhoaHoc = null;
    private ArrayList <Lop> dsLop = null;
    
    public SuaLop() {
        initComponents();
    }
    
    public void edit(){
        setLocationRelativeTo(null);
        //choiceKhoa.removeAll();
        Controller.addChoiceKhoa(choiceKhoa, dsKhoa);
        //choiceKhoa.add("");
        choiceKhoa.select("");
        Controller.addChoiceKhoaHoc(choiceKhoaHoc, dsKhoaHoc);
        
        Object  cell = table.getValueAt(chon, 1);
        String maLop = cell.toString();
        int temp = 0;
        for(Lop lop:dsLop){
            if(lop.getLop().equals(maLop)){
                temp = dsLop.indexOf(lop);
                break;
            }
        }
        Lop lop = dsLop.get(temp);
        jTextFieldLop.setText(maLop);
        choiceKhoa.select(Controller.doiMaKhoaThanhTenKhoa(lop.getMaKhoa(), dsKhoa));
        Controller.addChoiceCoVanTheoTen(choiceCoVan, dsCoVan, dsKhoa, lop.getMaCoVan());
        choiceCoVan.select(Controller.doiMaCVThanhTen(lop.getMaCoVan(), dsCoVan));
        choiceKhoaHoc.select(lop.getMaKhoaHoc());
        jTextFieldName.setText(Controller.doiMaCVThanhTen(lop.getMaCoVan(), dsCoVan));
        //for(int i=0)
        
        
        //Controller.addChoiceCoVan(choiceCoVan, dsCoVan);
    }
    
    public SuaLop(ArrayList <Khoa> dsKhoa, ArrayList <CoVan> dsCoVan, ArrayList <KhoaHoc> dsKhoaHoc, ArrayList <Lop> dsLop, JTable table, Choice choice, int chon) {
        this.dsKhoa = dsKhoa;
        this.dsCoVan = dsCoVan;
        this.dsKhoaHoc = dsKhoaHoc;
        this.table = table;
        this.dsLop = dsLop;
        this.choice = choice;
        this.chon = chon;
        initComponents();
        edit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldLop = new javax.swing.JTextField();
        jLabelLop1 = new javax.swing.JLabel();
        jLabelSubmit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLop = new javax.swing.JLabel();
        choiceKhoa = new java.awt.Choice();
        jLabelLop2 = new javax.swing.JLabel();
        choiceKhoaHoc = new java.awt.Choice();
        jPanel2 = new javax.swing.JPanel();
        jLabelLop3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        choiceCoVan = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("CẬP NHẬT THÔNG TIN LỚP");
        jPanelMain.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 402, 38));

        jTextFieldLop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldLop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelMain.add(jTextFieldLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 54, 340, 41));

        jLabelLop1.setText("Lớp");
        jPanelMain.add(jLabelLop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, -1));

        jLabelSubmit.setBackground(new java.awt.Color(221, 51, 51));
        jLabelSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubmit.setText("CẬP NHẬT");
        jLabelSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSubmit.setOpaque(true);
        jLabelSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSubmitMouseClicked(evt);
            }
        });
        jPanelMain.add(jLabelSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 390, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLop.setText("Khoa");

        choiceKhoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceKhoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        choiceKhoa.setPreferredSize(new java.awt.Dimension(28, 50));
        choiceKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choiceKhoaMouseClicked(evt);
            }
        });
        choiceKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceKhoaItemStateChanged(evt);
            }
        });

        jLabelLop2.setText("Khóa học");

        choiceKhoaHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceKhoaHoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        choiceKhoaHoc.setPreferredSize(new java.awt.Dimension(28, 50));
        choiceKhoaHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceKhoaHocItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelLop)
                .addGap(19, 19, 19)
                .addComponent(choiceKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLop2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(choiceKhoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabelLop2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanelMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLop3.setText("Cố vấn");

        jTextFieldName.setEditable(false);
        jTextFieldName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        choiceCoVan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceCoVan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        choiceCoVan.setPreferredSize(new java.awt.Dimension(28, 50));
        choiceCoVan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceCoVanItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelLop3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceCoVan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLop3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(choiceCoVan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 390, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiceKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceKhoaItemStateChanged
        // TODO add your handling code here:
        Controller.addChoiceCoVanTheoTen(choiceCoVan, dsCoVan, dsKhoa, choiceKhoa.getSelectedItem());
    }//GEN-LAST:event_choiceKhoaItemStateChanged

    private void choiceKhoaHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceKhoaHocItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_choiceKhoaHocItemStateChanged

    private void choiceCoVanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceCoVanItemStateChanged
        // TODO add your handling code here:
        String ten = Controller.doiMaCVThanhTen(choiceCoVan.getSelectedItem(), dsCoVan);
        jTextFieldName.setText(ten);
    }//GEN-LAST:event_choiceCoVanItemStateChanged

    private void jLabelSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubmitMouseClicked
        if(jTextFieldLop.getText().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            if(JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn sửa không?") == JOptionPane.YES_OPTION) {
                
                Object  cell = table.getValueAt(chon, 1);
                String maLop = cell.toString();
                int temp = 0;
                for(int i=0; i<dsLop.size(); i++){
                    if(dsLop.get(i).getLop().equals(maLop)){
                        temp = i;
                        break;
                    }
                }
                System.out.println(temp);
                if(!maLop.equals(jTextFieldLop.getText().toUpperCase())){
                    if(Controller.isRepeatLop(dsLop, jTextFieldLop.getText().toUpperCase())){
                        JOptionPane.showMessageDialog(rootPane, "Lớp đã có trên hệ thống!");
                        return;
                    }
                }
                
                dsLop.get(temp).setLop(jTextFieldLop.getText().toUpperCase());
                dsLop.get(temp).setMaKhoa(Controller.doiTenKhoaThanhMaKhoa(choiceKhoa.getSelectedItem(), dsKhoa));
                dsLop.get(temp).setMaKhoaHoc(choiceKhoaHoc.getSelectedItem());
                if(choiceCoVan.getSelectedItem()!=null){
                    dsLop.get(temp).setMaCoVan(choiceCoVan.getSelectedItem());
                }
                Controller.addListToLop(dsLop);
                if(choice.getSelectedItem().trim().equals("Tất cả")){
                    Controller.addListLopToTable(dsLop, table, dsKhoa, dsCoVan);
                } else {
                    Controller.addListLopToTable_Khoa(dsLop, table, dsKhoa, dsCoVan, Controller.doiTenKhoaThanhMaKhoa(choice.getSelectedItem(), dsKhoa));
                }
                
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jLabelSubmitMouseClicked

    private void choiceKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choiceKhoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceKhoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choiceCoVan;
    private java.awt.Choice choiceKhoa;
    private java.awt.Choice choiceKhoaHoc;
    private javax.swing.JLabel jLabelLop;
    private javax.swing.JLabel jLabelLop1;
    private javax.swing.JLabel jLabelLop2;
    private javax.swing.JLabel jLabelLop3;
    private javax.swing.JLabel jLabelSubmit;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldLop;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
